name: "Mandy site build."
description: "A GitHub action to build your Mandy-powered project!"
icon: "activity"
color: "purple"
runs:
  using: "composite"
  steps:
    - name: "Installing Rust."
      uses: "actions-rs/toolchain@v1"
      with:
        toolchain: "stable"
    - name: "Install Mandy."
      shell: bash
      run: "cargo install --git https://github.com/angeldollface/mandy.git mandy-bin --tag v.0.3.0"
